name: SweetPlayerMarket
version: '${version}'
main: top.mrxiaom.sweet.playermarket.SweetPlayerMarket
api-version: 1.13
softdepend:
  - Vault
  - PlayerPoints
  - MPoints
  - PlaceholderAPI
  - LangUtils
authors: [ MrXiaoM ]
folia-supported: true
libraries:
  - "org.jetbrains:annotations:24.0.0"
commands:
  sweetplayermarket:
    description: 'The main command of SweetPlayerMarket'
    aliases: [ spm, pm, playermarket ]
